album/album/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('albumapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

album/albumapp/urls.py
from . import views
from django.urls import path
app_name='albumapp'
urlpatterns =[
    path('',views.home, name='home'),
    path('eng/',views.eng, name='engagement.html'),
    path('mk_sreya/',views.mk_sreya, name='mk_sreya.html'),
    path('mk_sethu/',views.mk_sethu, name='mk_sethu.html'),
    path('wedding/',views.wedding, name='wedding.html')
]

album/albumapp/models.py
from django.db import models


# Create your models here.
class Engagement(models.Model):
    e_img = models.ImageField(upload_to='gallery')

class Mk_sreya(models.Model):
    mk_sreya_img = models.ImageField(upload_to='gallery')

class Mk_sethu(models.Model):
    mk_sethu_img = models.ImageField(upload_to='gallery')

class Wedding(models.Model):
    wedding_img = models.ImageField(upload_to='gallery')

album/albumapp/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Engagement, Mk_sreya, Mk_sethu, Wedding


def home(request):
    return render(request,"home.html")

def eng(request):
    e = Engagement.objects.all()
    content = {'engagement_list': e}
    return render(request, "engagement.html", content)

def mk_sreya(request):
    mk_sreya = Mk_sreya.objects.all()
    content = {'mk_sreya_list': mk_sreya}
    return render(request, "mk_sreya.html", content)

def mk_sethu(request):
    mk_sethu = Mk_sethu.objects.all()
    content = {'mk_sethu_list': mk_sethu}
    return render(request, "mk_sethu.html", content)

def wedding(request):
    wedding = Wedding.objects.all()
    content = {'wedding_list': wedding}
    return render(request, "wedding.html", content)

album/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Niconne&display=swap" rel="stylesheet">
    <<link href="https://fonts.googleapis.com/css2?family=Yatra+One&display=swap" rel="stylesheet">



    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div>
        {% include 'header.html' %}

        {% block content %}
        {% endblock %}
    </div>
    {% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

album/templates/engagement.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

         Forever and always!

{% endblock %}
{% block title %}
    e album- Sreya & Sethu
{% endblock %}
{% block content%}
<h1 class="text-center my_title1">Engagement Photos</h1>


<!--<div class="container">-->
<!--    <div class="row">-->
        {% for i in engagement_list %}
<!--        <div class="col-md-3">-->
            <center><img src="{{i.e_img.url}}" alt="Card image not loading :/"></div></center>
            <br>

<!--        </div>-->
<!--    </div>-->
        {% endfor %}

{% endblock %}

album/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center"> &copy; SreyaWedsSethu </p>
</div>

album/templates/header.html
{% load static %}
<header>
    <div class="header navbar-fixed-bottom my_header">
    <center>
        <a href="{%url 'albumapp:home' %}"><img src="{% static 'img/logo.gif' %}" alt=" no logoimage" width ="100px";></a>
    </center>
    </div>
</header>

album/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

         Forever and always!

{% endblock %}
{% block title %}
    e album- Sreya & Sethu
{% endblock %}
{% block content%}
<br>
<div>
    <h1 class="text-center my_title1">Sreya & Sethu</h1>
        <h5 class="text-center my_title7"><center>6 years worth of memories later and we’ve backpacked through India, renovated our dream home and introduced 2 furry pups to our family. A few months ago Harry finally popped the question over coffee and croissants, back at our favorite cafe where it all began, and Sally said yes. We can’t wait for this exciting new chapter to begin!</center></h5>
        <h2 class="text-center my_title2">Occations</h2>
</div>


<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="shadow p-3 mb-5 bg-body rounded">
                <div class="card" style="width: 17rem;">
                    <img class="card-img-top" src="{% static 'img/engagement_cover.jpg' %}" width="170" height="325" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title"><center>28 Dec 2022</center></h5>
                            <center><a href="/eng" class="btn btn-outline-primary"><h1 class="text-center my_title3">Engagement</h1></a></center>
                         </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="shadow p-3 mb-5 bg-body rounded">
                <div class="card" style="width: 17rem;">
                    <img class="card-img-top" src="{% static 'img/maduram_sreya_cover.png' %}" width="170" height="325" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title"><center>30 Dec 2022</center></h5>
                            <center><a href="/mk_sreya" class="btn btn-outline-primary"><h1 class="text-center my_title4">Maduram Kodukkal- Sreya</h1></a></center>
                        </div>
                </div>
            </div>
         </div>
    </div>
</div>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="shadow p-3 mb-5 bg-body rounded">
                <div class="card" style="width: 17rem;">
                    <img class="card-img-top" src="{% static 'img/maduram_sethu_cover.jfif' %}" width="170" height="325" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title"><center>01 Jan 2023</center></h5>
                            <center><a href="/mk_sethu" class="btn btn-outline-primary"><h1 class="text-center my_title5">Maduram Kodukkal- Sethu</h1></a></center>
                        </div>
                 </div>
            </div>
        </div>
    </div>
</div>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="shadow p-3 mb-5 bg-body rounded">
                <div class="card" style="width: 17rem;">
                    <img class="card-img-top" src="{% static 'img/wedding_cover.jfif' %}" width="170" height="325" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title"><center>02 Jan 2023</center></h5>
                            <center><a href="/wedding" class="btn btn-outline-primary"><h1 class="text-center my_title6">Wedding</h1></a></center>
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<br>

{% endblock %}

album/templates/mk_sethu.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

         Forever and always!

{% endblock %}
{% block title %}
    e album- Sreya & Sethu
{% endblock %}
{% block content%}
<h1 class="text-center my_title1">Maduram kodukal Photos- Sethu</h1>



        {% for i in mk_sethu_list %}

            <center><img src="{{i.mk_sethu_img.url}}" alt="Card image not loading :/"></div></center>
            <br>

        {% endfor %}

{% endblock %}

album/templates/mk_sreya.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

         Forever and always!

{% endblock %}
{% block title %}
    e album- Sreya & Sethu
{% endblock %}
{% block content%}
<h1 class="text-center my_title1">Maduram kodukal Photos- Sreya</h1>



        {% for i in mk_sreya_list %}

            <center><img src="{{i.mk_sreya_img.url}}" alt="Card image not loading :/"></div></center>
            <br>

        {% endfor %}

{% endblock %}

album/templates/wedding.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

         Forever and always!

{% endblock %}
{% block title %}
    e album- Sreya & Sethu
{% endblock %}
{% block content%}
<h1 class="text-center my_title1">Wedding Photos</h1>



        {% for i in wedding_list %}

            <center><img src="{{i.wedding_img.url}}" alt="Card image not loading :/"></div></center>
            <br>

        {% endfor %}

{% endblock %}